### ISSUE TITLE
fastdfs-nginx chart configmap文件的问题

### ISSUE THREAD

**Issue by NuiStrawBerry** [ygqygq2/charts#17]
文件 https://github.com/ygqygq2/charts/blob/fastdfs-nginx-2.0.0/ygqygq2/fastdfs-nginx/templates/configmap.yaml

第42行 proxy_pass 直接写为group1有问题，如果配置多个group则只能访问group1其他的group无法访问，这里应该是个变量。 不知道我的理解是否正确

**Comment by lingxiao26** [comment]
是的, 这块写死了
`   {{- range $skey, $svalue := $.Values.fastdfs.storage }}
        location ~/{{ $svalue.name }}/ {
            #proxy_pass http://fdfs_group1;
            proxy_pass http://fdfs_{{ $svalue.name }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        {{- end }}`
