### ISSUE TITLE
[BUG] 多余的字段

### ISSUE THREAD

**Issue by hzux** [ygqygq2/charts#61]
https://github.com/ygqygq2/charts/blob/master/ygqygq2/mod-chart/templates/deployment-statefulset.yaml#L253

这里的 annotations 应该是不存在的

**Comment by ygqygq2** [comment]
![image](https://github.com/user-attachments/assets/d2aa9dd2-7fa8-4d75-8ea8-e254405a39bf)
没明白你说的，这个是 pvc 的，可以设置注解，pvc 即使在 helm uninstall 时保留什么的。

**Comment by hzux** [comment]
pvc 注解是上面的 metadata.annotations
重复的这个是 spec.annotations，spec 下是没有 annotations 的
参考 https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaimSpec

**Comment by ygqygq2** [comment]
是的，感谢，我修复下，k8s 也多了不少功能，我找时间弄版新的。

**Comment by hzux** [comment]
是我该谢你，你的开源给我很大帮助
